<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cairn-server</AssemblyName>
    <RootNamespace>Cairn.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Cairn.Core/Cairn.Core.csproj" />
  </ItemGroup>
</Project>
